"""
Regenerate static-site data files:
  - data/samples_<sport>.js          → window.SAMPLES (used by both studies)
  - data/style_judge_<sport>.js      → window.STYLE_JUDGE (writing-style scores
                                       shown as a reference on style.html)

Sources:
  - human_study_samples_<sport>_subset.json  (sample text / facts)
  - model_style_<sport>_subset.json          (writing-style judge scores)
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SPORTS = ["basketball", "hockey", "soccer"]


def write_js(dst, varname, value, header):
    with open(dst, "w") as f:
        f.write(f"// Auto-generated by build_data.py — do not edit by hand. ({header})\n")
        f.write(f"window.{varname} = ")
        json.dump(value, f, indent=2, ensure_ascii=False)
        f.write(";\n")


def main():
    for sport in SPORTS:
        # Samples
        src = os.path.join(HERE, "..", f"human_study_samples_{sport}_subset.json")
        dst = os.path.join(HERE, "data", f"samples_{sport}.js")
        if os.path.exists(src):
            with open(src) as f:
                samples = json.load(f)
            write_js(dst, "SAMPLES", samples, sport)
            print(f"Wrote {len(samples)} samples ({sport}) -> {dst}")
        else:
            print(f"  skip samples ({sport}): {src} not found")

        # Style-judge reference (compact: just the per-sample scores, no responses)
        src_j = os.path.join(HERE, "..", f"model_style_{sport}_subset.json")
        dst_j = os.path.join(HERE, "data", f"style_judge_{sport}.js")
        if os.path.exists(src_j):
            with open(src_j) as f:
                rows = json.load(f)
            compact = [{
                "id": r["id"],
                "component_id": r["component_id"],
                "model": r["model"],
                "stylistic": r.get("judge_stylistic_score"),
                "narrative": r.get("judge_narrative_score"),
                "overall":   r.get("judge_overall_score"),
            } for r in rows]
            write_js(dst_j, "STYLE_JUDGE", compact, f"{sport} style judge")
            print(f"Wrote {len(compact)} style-judge rows ({sport}) -> {dst_j}")
        else:
            print(f"  skip style judge ({sport}): {src_j} not found")


if __name__ == "__main__":
    main()
