"""
Regenerate github_pages/data/samples_basketball.js from the subset JSON.
Run after changing the subset.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "human_study_samples_basketball_subset.json")
DST = os.path.join(HERE, "data", "samples_basketball.js")


def main():
    with open(SRC) as f:
        samples = json.load(f)

    with open(DST, "w") as f:
        f.write("// Auto-generated by build_data.py — do not edit by hand.\n")
        f.write("const SAMPLES = ")
        json.dump(samples, f, indent=2, ensure_ascii=False)
        f.write(";\n")

    print(f"Wrote {len(samples)} samples -> {DST}")


if __name__ == "__main__":
    main()
